/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 earth.gltf --transform
Author: kaede256 (https://sketchfab.com/kaede256)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/planet-earth-bce3ea48781c4f02a8c52d2678220d07
Title: Planet Earth
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import Models from '../../assets/models/modeldata';

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(Models[0].src)
  const { actions } = useAnimations(animations, group)

  useFrame(({ clock }) => {
    const elapsedTime = clock.getElapsedTime();
    group.current.rotation.y = elapsedTime * 0.1; // Adjust the rotation speed as needed
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.01}>
          <group name="Earth" rotation={[-Math.PI / 2, 0, 0.681]} scale={358.622}>
            <group name="Earth_Details" position={[0.163, -0.812, 0.592]} rotation={[-0.525, -0.789, -2.962]} scale={[0.006, 0.006, 0.009]}>
              <mesh name="Earth_Details_Wood_0" geometry={nodes.Earth_Details_Wood_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="Clouds_and_Stars" position={[-0.577, -0.085, 0.844]} rotation={[-1.555, -0.135, 2.627]} scale={0.042}>
              <mesh name="Clouds_and_Stars_Ice_0" geometry={nodes.Clouds_and_Stars_Ice_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <mesh name="Earth_Ice_0" geometry={nodes.Earth_Ice_0.geometry} material={materials.PaletteMaterial001} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(Models[0].src)
