/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 moon.gltf --transform
Author: drei.lu (https://sketchfab.com/drei.lu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-exploration-wlp-series-8-91964c1ce1a34c3985b6257441efa500
Title: Space exploration [WLP series #8]
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations} from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import Models from '../../assets/models/modeldata';

export default function Model(props) {
  const { nodes, materials, animations} = useGLTF(Models[1].src)
  const group = useRef()
  const { actions } = useAnimations(animations, group)
  useFrame(({ clock }) => {
    const elapsedTime = clock.getElapsedTime();
    group.current.rotation.y = elapsedTime * 0.1; // Adjust the rotation speed as needed
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.planet001.geometry} material={materials.scene} position={[-0.003, -6.331, -0.024]} rotation={[-1.333, -0.545, 0.562]} scale={7} />
    </group>
  )
}

useGLTF.preload(Models[1].src)
